### PR TITLE
Add test for prefab loading and releasing

### PR DESCRIPTION
**Pull request by mattbenic**
Just testing if dynamically created prefabs not releasing is Atomic or not. Seems not, and it's a test worth keeping.
To keep the code clearer and consistent, also moved the texture swapping into a component

### CODE REVIEW

**Comment by JoshEngebretson** [comment]
In my GC/lifetime work branch in the Luma fork the prefab is being released properly, is this where this was tested? I'll look into the dynamic texture surviving scene unloads.

**Comment by JoshEngebretson** [comment]
I am noticing 3 nodes left, though overall nodes aren't growing, can verify what is going on there.  BTW, is PrefabLoader.cs supposed to be empty? https://github.com/AtomicGameEngine/AtomicTests/blob/master/CSharpTests/SceneResourcesTest/Resources/Components/PrefabLoader.cs

**Comment by JoshEngebretson** [comment]
Ok, I tracked the 3 nodes and they are shadow camera nodes, which aren't leaking: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Graphics/Renderer.cpp#L1131

Thinking part of this test is missing, which may show the issue, will look into the dynamic textures once confirmed :)

**Comment by mattbenic** [comment]
Yeah as I said in the description (and gitter) it was just a useful test to keep. It doesn't represent something that fails.

**Comment by JoshEngebretson** [comment]
Darn, double negative, they are not, not releasing :)  Ok, great... I think the textures not releasing is a failure?  Does PrefabLoader.cs have some code to go with it?  I notice it is referenced in the test scene...

**Comment by mattbenic** [comment]
It does, not sure how it pushed empty :/ It just loads a prefab from an inspector set path

**Pull request merged**
